1 test retrodetect
SheffieldMLtracking/retrodetect pull request #2
Opened 2024-03-18 13:07 UTC by Shiminc

Hi Joe,
I think, hopefully, I have finished writing all the tests and docstr for the retrodect.

In relation to testing the output 'contact' from the detectcontact, I was trying using json, as suggested by you last week. Unfortunately, the 'contact' list of dictionaries contains obj not in line with json, mainly the numpy array. So I resorted to pickle again.

In terms of docstr for all the functions, I actually relied on Gemini, although I did read through and edit based on my very limited understanding.

Not sure if the next step will be to test publishing it to a package. let me know.

Thanks
Shi Min

2024-03-18 13:24 UTC, Joe-Heffer-Shef requested changes

2024-03-18 13:24 UTC, Joe-Heffer-Shef commented on .github/workflows/python-package.yml
> +    branches: [ "1-test-retrodetect" ]
This can be changed to
```
on: [push, pull_request]
```
so it'll run for any pull - that way  you don't need to keep manually changing it

2024-03-18 13:24 UTC, Joe-Heffer-Shef commented on src/retrodetect/detect.py
> +        #    photoitem['img'][0, 0], numbers.Integral), "Need image array to be float not integers." #SC:check one of the number of the img array # I think we need to force it
It's better to delete code rather than comment it out

2024-03-18 16:33 UTC, Shiminc commented on .github/workflows/python-package.yml
> +    branches: [ "1-test-retrodetect" ]
yay!

2024-03-18 16:34 UTC, Shiminc commented on src/retrodetect/detect.py
> +        #    photoitem['img'][0, 0], numbers.Integral), "Need image array to be float not integers." #SC:check one of the number of the img array # I think we need to force it
okay I have deleted all the codes that have been commented out by myself and mike

2024-03-19 09:27 UTC, Joe-Heffer-Shef approved these changes

2024-03-19 09:33 UTC, merged